<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/config/action_filters.xml
// Generated by: AgaviFilterConfigHandler
// Date: 2009-02-20T11:31:45+0000

$filter = new AgaviExecutionTimeFilter();
$filter->initialize($this->context, array (
  'comment' => true,
  'output_types' => 
  array (
    0 => 'html',
  ),
));
$filters[] = $filter;

?>