<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/modules/Welcome/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2009-02-20T11:31:45+0000

return array (
  'BlogWelcomeBaseAction' => '/Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/modules/Welcome/lib/action/BlogWelcomeBaseAction.class.php',
  'BlogWelcomeBaseModel' => '/Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/modules/Welcome/lib/model/BlogWelcomeBaseModel.class.php',
  'BlogWelcomeBaseView' => '/Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/modules/Welcome/lib/view/BlogWelcomeBaseView.class.php',
);

?>