<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/config/compile.xml
// Generated by: AgaviCompileConfigHandler
// Date: 2009-02-20T11:31:45+0000

require('/Users/fgilcher/Sites/agavi/branches/1.0/src/util/AgaviAttributeHolder.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/util/AgaviArrayPathDefinition.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/action/AgaviAction.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/core/AgaviContext.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/controller/AgaviController.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/controller/AgaviExecutionContainer.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/controller/AgaviOutputType.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/filter/AgaviFilter.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/filter/AgaviDispatchFilter.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/filter/AgaviExecutionFilter.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/filter/AgaviFilterChain.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/renderer/AgaviRenderer.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/request/AgaviRequestDataHolder.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/request/AgaviRequest.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/response/AgaviResponse.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/routing/AgaviRouting.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/storage/AgaviStorage.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/user/AgaviUser.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/view/AgaviTemplateLayer.class.php');
require('/Users/fgilcher/Sites/agavi/branches/1.0/src/view/AgaviView.class.php');

?>