<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/fgilcher/Sites/agavi/documentation/branches/felix-tutorial-app-rewrite/stages/stage1/app/modules/Welcome/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2009-02-20T11:31:45+0000

return array (
)

?>