<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/modules/Default/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2009-09-16T14:38:36+0000

return array (
  'BlogDefaultBaseAction' => '/Users/sth/Sites/demoapp/app/modules/Default/lib/action/BlogDefaultBaseAction.class.php',
  'BlogDefaultBaseModel' => '/Users/sth/Sites/demoapp/app/modules/Default/lib/model/BlogDefaultBaseModel.class.php',
  'BlogDefaultBaseView' => '/Users/sth/Sites/demoapp/app/modules/Default/lib/view/BlogDefaultBaseView.class.php',
);

?>