<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/modules/Widgets/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2009-09-16T14:38:36+0000

return array (
  'BlogWidgetsBaseAction' => '/Users/sth/Sites/demoapp/app/modules/Widgets/lib/action/BlogWidgetsBaseAction.class.php',
  'BlogWidgetsBaseModel' => '/Users/sth/Sites/demoapp/app/modules/Widgets/lib/model/BlogWidgetsBaseModel.class.php',
  'BlogWidgetsBaseView' => '/Users/sth/Sites/demoapp/app/modules/Widgets/lib/view/BlogWidgetsBaseView.class.php',
);

?>