<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/config/compile.xml
// Generated by: AgaviCompileConfigHandler
// Date: 2009-09-16T14:38:36+0000

require('/Users/sth/Sites/demoapp/libs/agavi/util/AgaviAttributeHolder.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/util/AgaviArrayPathDefinition.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/action/AgaviAction.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/core/AgaviContext.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/controller/AgaviController.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/controller/AgaviExecutionContainer.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/controller/AgaviOutputType.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/filter/AgaviFilter.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/filter/AgaviDispatchFilter.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/filter/AgaviExecutionFilter.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/filter/AgaviFilterChain.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/renderer/AgaviRenderer.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/request/AgaviRequestDataHolder.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/request/AgaviRequest.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/response/AgaviResponse.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/routing/AgaviRouting.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/storage/AgaviStorage.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/user/AgaviUser.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/view/AgaviTemplateLayer.class.php');
require('/Users/sth/Sites/demoapp/libs/agavi/view/AgaviView.class.php');

?>