<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/modules/Default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2009-09-16T14:38:36+0000

return array (
)

?>