<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2009-09-16T14:38:36+0000

return array (
  '/Users/sth/Sites/demoapp/app/config/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/autoload.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/autoload.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/libs/agavi/config/defaults/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/autoload.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/autoload.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/compile.xml' => 
  array (
    'class' => 'AgaviCompileConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/compile.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/compile.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/libs/agavi/config/defaults/compile.xml' => 
  array (
    'class' => 'AgaviCompileConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/compile.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/compile.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/settings.xml' => 
  array (
    'class' => 'AgaviSettingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/settings.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/settings.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/factories.xml' => 
  array (
    'class' => 'AgaviFactoryConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/factories.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/factories.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/databases.xml' => 
  array (
    'class' => 'AgaviDatabaseConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/databases.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/databases.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/action_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/global_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/output_types.xml' => 
  array (
    'class' => 'AgaviOutputTypeConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/output_types.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/output_types.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/logging.xml' => 
  array (
    'class' => 'AgaviLoggingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/logging.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/logging.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/rbac_definitions.xml' => 
  array (
    'class' => 'AgaviRbacDefinitionConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/rbac_definitions.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/rbac_definitions.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/routing.xml' => 
  array (
    'class' => 'AgaviRoutingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/routing.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/libs/agavi/routing/soap/wsdl.xml' => 
  array (
    'class' => 'AgaviWsdlConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/routing/soap/wsdl.xsl',
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/config/translation.xml' => 
  array (
    'class' => 'AgaviTranslationConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/translation.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/translation.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '%core.testing_dir%/config/suites.xml' => 
  array (
    'class' => 'AgaviTestSuitesConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/modules/*/config/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/autoload.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/autoload.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/modules/*/config/action_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/modules/*/config/module.xml' => 
  array (
    'class' => 'AgaviModuleConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/module.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/module.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/modules/*/validate/*.xml' => 
  array (
    'class' => 'AgaviValidatorConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/validators.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/validators.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/app/modules/*/cache/*.xml' => 
  array (
    'class' => 'AgaviCachingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsl/caching.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/Users/sth/Sites/demoapp/libs/agavi/config/xsd/caching.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/libs/agavi/translation/data/locales/*.xml' => 
  array (
    'class' => 'AgaviLdmlConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/Users/sth/Sites/demoapp/libs/agavi/translation/data/supplementalData.xml' => 
  array (
    'class' => 'AgaviLdmlSupplementalConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
)

?>