<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/config/databases.xml
// Generated by: AgaviDatabaseConfigHandler
// Date: 2009-09-16T14:38:36+0000

$database = new AgaviPdoDatabase();
$this->databases['pdo_mysql_main'] = $database;
$database->initialize($this, array (
  'dsn' => 'sqlite:/Users/sth/Sites/demoapp/app/config/bloggie.db',
));
$this->defaultDatabaseName = 'pdo_mysql_main';

?>