<?php

// This is a compiled Agavi configuration file
// Compiled from: /Users/sth/Sites/demoapp/app/config/output_types.xml
// Generated by: AgaviOutputTypeConfigHandler
// Date: 2009-09-16T14:38:36+0000

$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/html; charset=UTF-8',
  ),
), 'html', array (
  'php' => 
  array (
    'class' => 'AgaviPhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
      'assigns' => 
      array (
        'routing' => 'ro',
        'request' => 'rq',
        'controller' => 'ct',
        'user' => 'us',
        'translation_manager' => 'tm',
        'request_data' => 'rd',
      ),
      'default_extension' => '.php',
      'var_name' => 't',
    ),
  ),
), 'php', array (
  'standard' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
      'decorator' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
          'directory' => '/Users/sth/Sites/demoapp/app/templates',
          'template' => 'Master',
        ),
        'renderer' => NULL,
        'slots' => 
        array (
          'navigation' => 
          array (
            'action' => 'Navigation',
            'module' => 'Widgets',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
          'header' => 
          array (
            'action' => 'Header',
            'module' => 'Widgets',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
          'footer' => 
          array (
            'action' => 'Footer',
            'module' => 'Widgets',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
          'dashboard' => 
          array (
            'action' => 'Dashboard',
            'module' => 'Widgets',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
          'sidebar' => 
          array (
            'action' => 'Sidebar',
            'module' => 'Widgets',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
  'wrapped' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
      'wrapper' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
          'extension' => '.wrapper.php',
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
      'decorator' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
          'directory' => '/Users/sth/Sites/demoapp/app/templates',
          'template' => 'Master',
        ),
        'renderer' => NULL,
        'slots' => 
        array (
          'nav' => 
          array (
            'action' => 'Widgets.Navigation',
            'module' => 'Default',
            'output_type' => NULL,
            'request_method' => NULL,
            'parameters' => 
            array (
            ),
          ),
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
  'slot' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'standard', NULL);
$this->outputTypes['html'] = $ot;
$ot = new AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/xml; charset=UTF-8',
  ),
), 'rss', array (
), NULL, array (
), NULL, NULL);
$this->outputTypes['rss'] = $ot;
$this->defaultOutputType = 'html';

?>